Added the boot-ro feature

diff --git a/etc/initramfs-tools/scripts/init-bottom/root-ro b/etc/initramfs-tools/scripts/init-bottom/root-ro
--- a/etc/initramfs-tools/scripts/init-bottom/root-ro
+++ b/etc/initramfs-tools/scripts/init-bottom/root-ro
@@ -79,118 +79,83 @@ esac
 # import /usr/share/initramfs-tools/scripts/functions
 . /scripts/functions
 
-MYTAG="root-ro"
-DISABLE_MAGIC_FILE="/disable-root-ro"
-
-# parse kernel boot command line 
-ROOT_RO_DRIVER=
-DISABLE_ROOT_RO=
-for CMD_PARAM in $(cat /proc/cmdline); do
-    case ${CMD_PARAM} in
-        disable-root-ro=*)
-            DISABLE_ROOT_RO=${CMD_PARAM#disable-root-ro=}
-            ;;
-        root-ro-driver=*)
-            ROOT_RO_DRIVER=${CMD_PARAM#root-ro-driver=}
-            ;;
-    esac
-done
-
-# check if read-only root fs is disabled
-if [ ! -z "${DISABLE_ROOT_RO}" ]; then
-    log_warning_msg "${MYTAG}: disabled, found boot parameter disable-root-ro=${DISABLE_ROOT_RO}"
-    exit 0
-fi
-if [ -e "${rootmnt}${DISABLE_MAGIC_FILE}" ]; then
-    log_warning_msg "${MYTAG}: disabled, found file ${rootmnt}${DISABLE_MAGIC_FILE}"
-    exit 0
-fi
-
-# generic settings
 # ${ROOT} and ${rootmnt} are predefined by caller of this script. Note that
 # the root fs ${rootmnt} it mounted readonly on the initrams, which fits nicely
 # for our purposes.
-ROOT_RO=/mnt/root-ro
-ROOT_RW=/mnt/root-rw
-ROOT_RW_UPPER=${ROOT_RW}/upper
-ROOT_RW_WORK=${ROOT_RW}/work
 
-# check if ${ROOT_RO_DRIVER} is defined, otherwise set default
-if [ -z "${ROOT_RO_DRIVER}" ]; then
-    ROOT_RO_DRIVER=overlay
-fi
-# settings based in ${ROOT_RO_DRIVER}, stop here if unsupported.
-case ${ROOT_RO_DRIVER} in
-    overlay)
-        MOUNT_PARMS="-t overlay -o lowerdir=${ROOT_RO},upperdir=${ROOT_RW_UPPER},workdir=${ROOT_RW_WORK} overlay ${rootmnt}"
-        ;;
-    aufs)
-        MOUNT_PARMS="-t aufs -o dirs=${ROOT_RW}:${ROOT_RO}=ro aufs-root ${rootmnt}"
-        ;;
-    *)
-        panic "${MYTAG} ERROR 1: invalid ROOT_RO_DRIVER ${ROOT_RO_DRIVER}"
-        ;;
-esac
-
-
-# check if kernel module exists
-modprobe -qb ${ROOT_RO_DRIVER}
+modprobe -qb overlay
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 2: missing kernel module ${ROOT_RO_DRIVER}"
+    log_failure_msg "ERROR 1: missing kernel module overlay"
     exit 0
 fi
 
-# make the mount point on the init root fs ${ROOT_RW}
-[ -d ${ROOT_RW} ] || mkdir -p ${ROOT_RW}
+# make the mount point on the init root fs /mnt/root-ro
+[ -d /mnt/root-ro ] || mkdir -p /mnt/root-ro
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 3: failed to create ${ROOT_RW}"
+    log_failure_msg "ERROR 2: failed to create /mnt/root-ro"
     exit 0
 fi
 
-# make the mount point on the init root fs ${ROOT_RO}
-[ -d ${ROOT_RO} ] || mkdir -p ${ROOT_RO}
+# make the mount point on the init root fs /mnt/root-rw
+[ -d /mnt/root-rw ] || mkdir -p /mnt/root-rw
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 4: failed to create ${ROOT_RO}"
+    log_failure_msg "ERROR 3: failed to create /mnt/root-rw"
     exit 0
 fi
 
-# make the mount point on the init root fs ${ROOT_WORKDIR}
-[ -d ${ROOT_WORKDIR} ] || mkdir -p ${ROOT_WORKDIR}
+# mount a tempfs using the device name tmpfs-root at /mnt/root-rw
+mount -t tmpfs tmpfs-root /mnt/root-rw
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 5: failed to create ${ROOT_WORKDIR}"
+    log_failure_msg "ERROR 4: failed to create tmpfs"
     exit 0
 fi
 
-
-# mount a tempfs using the device name tmpfs-root at ${ROOT_RW}
-mount -t tmpfs tmpfs-root ${ROOT_RW}
+[ -d /mnt/root-rw/upper ] || mkdir -p /mnt/root-rw/upper
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 6: failed to create tmpfs"
+	log_failure_msg "ERROR 5: failed to create /mnt/root-rw/upper"
+	exit 0
+fi
+
+[ -d /mnt/root-rw/work ] || mkdir -p /mnt/root-rw/work
+if [ $? -ne 0 ]; then
+	log_failure_msg "ERROR 6: failed to create /mnt/root-rw/work"
+	exit 0
+fi
+
+# root is mounted on ${rootmnt}, move it to /mnt/root-ro.
+mount -o move ${rootmnt} /mnt/root-ro
+if [ $? -ne 0 ]; then
+    log_failure_msg "ERROR 7: failed to move root away from ${rootmnt} to /mnt/root-ro"
     exit 0
 fi
 
-if [ "${ROOT_RO_DRIVER}" = "overlay" ]; then
-
-    [ -d ${ROOT_RW_UPPER} ] || mkdir -p ${ROOT_RW_UPPER}
-    if [ $? -ne 0 ]; then
-        log_failure_msg "${MYTAG} ERROR 6.1: failed to create ${ROOT_RW_UPPER}"
-        exit 0
-    fi
-
-    [ -d ${ROOT_RW_WORK} ] || mkdir -p ${ROOT_RW_WORK}
-    if [ $? -ne 0 ]; then
-        log_failure_msg "${MYTAG} ERROR 6.2: failed to create ${ROOT_RW_WORK}"
-        exit 0
-    fi
-
+# make the mount point on the init boot fs /mnt/boot-ro
+[ -d /mnt/boot-ro ] || mkdir -p /mnt/boot-ro
+if [ $? -ne 0 ]; then
+    log_failure_msg "ERROR 8: failed to create /mnt/boot-ro"
+    exit 0
 fi
 
-
-# root is mounted on ${rootmnt}, move it to ${ROOT_RO}.
-mount -o move ${rootmnt} ${ROOT_RO}
+# mount boot device to /mnt/boot-ro
+BOOTDEV=$(cat /mnt/root-ro/etc/fstab | awk '{if($2=="/boot")print $1}')
+mount -o ro $BOOTDEV /mnt/boot-ro
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 7: failed to move root away from ${rootmnt} to ${ROOT_RO}"
+    log_failure_msg "ERROR 9: failed to mount ${BOOTDEV} to /mnt/boot-ro"
     exit 0
+fi
+
+# create boot on upper directory
+[ -d /mnt/root-rw/upper/boot ] || mkdir -p /mnt/root-rw/upper/boot
+if [ $? -ne 0 ]; then
+	log_failure_msg "ERROR 10: failed to create /mnt/root-rw/upper/boot"
+	exit 0
+fi
+
+# copy all boot to upper directory
+rsync -va /mnt/boot-ro/* /mnt/root-rw/upper/boot/
+if [ $? -ne 0 ]; then
+	log_failure_msg "ERROR 11: failed to rsync from /mnt/boot-ro/* to /mnt/root-rw/upper/boot/"
+	exit 0
 fi
 
 # there is nothing left at ${rootmnt} now. So for any error we get we should
@@ -198,46 +163,54 @@ fi
 # "panic". Otherwise the boot process is very likely to fail with even more
 # errors and leave the system in a wired state.
 
-# mount virtual fs ${rootmnt} with rw-fs ${ROOT_RW} on top or ro-fs ${ROOT_RO}.
-mount ${MOUNT_PARMS}
+# mount virtual fs ${rootmnt} with rw-fs /mnt/root-rw on top or ro-fs /mnt/root-ro.
+mount -t overlay -o lowerdir=/mnt/root-ro,upperdir=/mnt/root-rw/upper,workdir=/mnt/root-rw/work overlay ${rootmnt}
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 8: failed to create new ro/rw layerd ${rootmnt}"
+    log_failure_msg "ERROR 12: failed to create new ro/rw layer on ${rootmnt}"
     # do recovery and try resoring the mount for ${rootmnt}
-    mount -o move ${ROOT_RO} ${rootmnt}
+    mount -o move /mnt/root-ro ${rootmnt}
     if [ $? -ne 0 ]; then
        # thats bad, drop to shell to let the user try fixing this
-       panic "${MYTAG} RECOVERY ERROR: failed to move ${ROOT_RO} back to ${rootmnt}"
+       panic "ERROR 13: failed to move /mnt/root-ro back to ${rootmnt}"
     fi
     exit 0
 fi
 
-# now the real root fs is on ${ROOT_RO} of the init file system, our layered
+# now the real root fs is on /mnt/root-ro of the init file system, our layered
 # root fs is set up at ${rootmnt}. So we can write anywhere in {rootmnt} and the
-# changes will end up in ${ROOT_RW} while ${ROOT_RO} it not touched. However
-# ${ROOT_RO} and ${ROOT_RW} are on the initramfs root fs, which will be removed
-# an replaced by ${rootmnt}. Thus we must move ${ROOT_RO} and ${ROOT_RW} to the
-# rootfs visible later, ie. ${rootmnt}${ROOT_RO} and ${rootmnt}${ROOT_RO}.
+# changes will end up in /mnt/root-rw while /mnt/root-ro it not touched. However
+# /mnt/root-ro and /mnt/root-rw are on the initramfs root fs, which will be removed
+# an replaced by ${rootmnt}. Thus we must move /mnt/root-ro and /mnt/root-rw to the
+# rootfs visible later, ie. ${rootmnt}/mnt/root-ro and ${rootmnt}/mnt/root-rw.
 # Since the layered ro/rw is already up, these changes also end up on
-# ${ROOT_RW} while ${ROOT_RO} is not touched.
+# /mnt/root-rw while /mnt/root-ro is not touched.
 
-# move mount from ${ROOT_RO} to ${rootmnt}${ROOT_RO}
-[ -d ${rootmnt}${ROOT_RO} ] || mkdir -p ${rootmnt}${ROOT_RO}
-mount -o move ${ROOT_RO} ${rootmnt}${ROOT_RO}
+# move mount from /mnt/root-ro to ${rootmnt}/mnt/root-ro
+[ -d ${rootmnt}/mnt/root-ro ] || mkdir -p ${rootmnt}/mnt/root-ro
+mount -o move /mnt/root-ro ${rootmnt}/mnt/root-ro
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 9: failed to move ${ROOT_RO} to ${rootmnt}${ROOT_RO}"
+    log_failure_msg "ERROR 14: failed to move /mnt/root-ro to ${rootmnt}/mnt/root-ro"
     exit 0
 fi
 
-# move mount from ${ROOT_RW} to ${rootmnt}${ROOT_RW}
-[ -d ${rootmnt}${ROOT_RW} ] || mkdir -p ${rootmnt}${ROOT_RW}
-mount -o move ${ROOT_RW} ${rootmnt}${ROOT_RW}
+# move mount from /mnt/root-rw to ${rootmnt}/mnt/root-rw
+[ -d ${rootmnt}/mnt/root-rw ] || mkdir -p ${rootmnt}/mnt/root-rw
+mount -o move /mnt/root-rw ${rootmnt}/mnt/root-rw
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG}: ERROR 10: failed to move ${ROOT_RW} to ${rootmnt}${ROOT_RW}"
+    log_failure_msg "ERROR 15: failed to move /mnt/root-rw to ${rootmnt}/mnt/root-rw"
+    exit 0
+fi
+
+# move mount from /mnt/boot-ro to ${rootmnt}/mnt/boot-ro
+[ -d ${rootmnt}/mnt/boot-ro ] || mkdir -p ${rootmnt}/mnt/boot-ro
+mount -o move /mnt/boot-ro ${rootmnt}/mnt/boot-ro
+if [ $? -ne 0 ]; then
+    log_failure_msg "ERROR 16: failed to move /mnt/boot-ro to ${rootmnt}/mnt/boot-ro"
     exit 0
 fi
 
 # technically, everything is set up nicely now. Since ${rootmnt} had beend
-# mounted read-only on the initfamfs already, ${rootmnt}${ROOT_RO} is it, too.
+# mounted read-only on the initfamfs already, ${rootmnt}/mnt/root-ro is it, too.
 # Now we init process could run - but unfortunately, we may have to prepare
 # some more things here.
 # Basically, there are two ways to deal with the read-only root fs. If the
@@ -248,44 +221,44 @@ fi
 #
 # Let's deal with /etc/fstab first. It usually contains an entry for the root
 # fs, which is no longer valid now. We have to remove it and add our new
-# ${ROOT_RO} entry.
+# /mnt/root-ro entry.
 # Remember we are still on the initramfs root fs here, so we have to work on
-# ${rootmnt}/etc/fstab. The original fstab is ${rootmnt}${ROOT_RO}/etc/fstab.
-ROOT_TYPE=$(cat /proc/mounts | ${rootmnt}/bin/grep ${ROOT} | ${rootmnt}/usr/bin/cut -d' ' -f3)
-ROOT_OPTIONS=$(cat /proc/mounts | ${rootmnt}/bin/grep ${ROOT} | ${rootmnt}/usr/bin/cut -d' ' -f4)
+# ${rootmnt}/etc/fstab. The original fstab is ${rootmnt}/mnt/root-ro/etc/fstab.
+ROOT_TYPE=$(cat /proc/mounts | grep ${ROOT} | cut -d' ' -f3)
+ROOT_OPTIONS=$(cat /proc/mounts | grep ${ROOT} | cut -d' ' -f4)
+BOOT_TYPE=$(cat /proc/mounts | grep ${BOOTDEV} | cut -d' ' -f3)
+BOOT_OPTIONS=$(cat /proc/mounts | grep ${BOOTDEV} | cut -d' ' -f4)
 cat <<EOF >${rootmnt}/etc/fstab
 #
-#  This fstab is in RAM, the real one can be found at ${ROOT_RO}/etc/fstab
+#  This fstab is in RAM, the real one can be found at /mnt/root-ro/etc/fstab
 #  The original entry for '/' and all swap files have been removed.  The new
 #  entry for the read-only the real root fs follows. Write access can be
 #  enabled using:
-#    sudo mount -o remount,rw ${ROOT_RO}
+#    sudo mount -o remount,rw /mnt/root-ro
 #  re-mounting it read-only is done using:
-#    sudo mount -o remount,ro ${ROOT_RO}
+#    sudo mount -o remount,ro /mnt/root-ro
 #
-
-${ROOT} ${ROOT_RO} ${ROOT_TYPE} ${ROOT_OPTIONS} 0 0
-
+${BOOTDEV} /mnt/boot-ro ${BOOT_TYPE} ${BOOT_OPTIONS} 0 0
+${ROOT} /mnt/root-ro ${ROOT_TYPE} ${ROOT_OPTIONS} 0 0
 #
-#  remaining entries from the original ${ROOT_RO}/etc/fstab follow.
+#  remaining entries from the original /mnt/root-ro/etc/fstab follow.
 #
 EOF
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 11: failed to modify /etc/fstab (step 1)"
+    log_failure_msg "ERROR 17: failed to modify /etc/fstab (step 1)"
     #exit 0
 fi
 
-#remove root entry and swap from fstab
-#cat ${rootmnt}${ROOT_RO}/etc/fstab | ${rootmnt}/bin/grep -v ' / ' | ${rootmnt}/bin/grep -v swap >> ${rootmnt}/etc/fstab
-cat ${rootmnt}${ROOT_RO}/etc/fstab | awk '{if($2!="/"&&$2!="swap"){if($2=="/boot")$4="ro,"$4;print $0}}' >> ${rootmnt}/etc/fstab
+#remove root, boot and swap from fstab
+cat ${rootmnt}/mnt/root-ro/etc/fstab | awk '{if($2!="/"&&$2!="/boot"&&$2!="swap")print $0}' >> ${rootmnt}/etc/fstab
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 12: failed to modify etc/fstab (step 2)"
+    log_failure_msg "ERROR 18: failed to modify etc/fstab (step 2)"
     #exit 0
 fi
 
 # now we are done. Additinal steps may be necessary depending on the actualy
 # distribution and/or its configuration.
 
-log_success_msg "${MYTAG} sucessfully set up ro/tmpfs-rw layered root fs using ${ROOT_RO_DRIVER}"
+log_success_msg "Sucessfully set up ro/rw/tmpfs layer for root and boot fs using overlay"
 
 exit 0
